apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: springboot-app-ingress
  annotations:
    kubernetes.io/ingress.class: "gce"
    kubernetes.io/ingress.global-static-ip-name: "springboot-app-ip"
spec:
  defaultBackend:
    service:
      name: springboot-app-service
      port:
        number: 80
